/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated.tasks'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AuthenticatedKnowledgeRouteImport } from './routes/_authenticated.knowledge'
import { Route as AuthenticatedContactsRouteImport } from './routes/_authenticated.contacts'
import { Route as AuthenticatedCompaniesRouteImport } from './routes/_authenticated.companies'
import { Route as AuthenticatedTasksNewRouteImport } from './routes/_authenticated.tasks.new'
import { Route as AuthenticatedTasksIdRouteImport } from './routes/_authenticated.tasks.$id'
import { Route as AuthenticatedKnowledgeNewRouteImport } from './routes/_authenticated.knowledge.new'
import { Route as AuthenticatedKnowledgeIdRouteImport } from './routes/_authenticated.knowledge.$id'
import { Route as AuthenticatedJourneysNewRouteImport } from './routes/_authenticated.journeys.new'
import { Route as AuthenticatedJourneysIdRouteImport } from './routes/_authenticated.journeys.$id'
import { Route as AuthenticatedContactsNewRouteImport } from './routes/_authenticated.contacts.new'
import { Route as AuthenticatedContactsIdRouteImport } from './routes/_authenticated.contacts.$id'
import { Route as AuthenticatedCompaniesNewRouteImport } from './routes/_authenticated.companies.new'
import { Route as AuthenticatedCompaniesIdRouteImport } from './routes/_authenticated.companies.$id'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated.admin.users'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedKnowledgeRoute = AuthenticatedKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContactsRoute = AuthenticatedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCompaniesRoute = AuthenticatedCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTasksNewRoute = AuthenticatedTasksNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedTasksRoute,
} as any)
const AuthenticatedTasksIdRoute = AuthenticatedTasksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedTasksRoute,
} as any)
const AuthenticatedKnowledgeNewRoute =
  AuthenticatedKnowledgeNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedKnowledgeRoute,
  } as any)
const AuthenticatedKnowledgeIdRoute =
  AuthenticatedKnowledgeIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedKnowledgeRoute,
  } as any)
const AuthenticatedJourneysNewRoute =
  AuthenticatedJourneysNewRouteImport.update({
    id: '/journeys/new',
    path: '/journeys/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedJourneysIdRoute = AuthenticatedJourneysIdRouteImport.update({
  id: '/journeys/$id',
  path: '/journeys/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContactsNewRoute =
  AuthenticatedContactsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedContactsRoute,
  } as any)
const AuthenticatedContactsIdRoute = AuthenticatedContactsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedContactsRoute,
} as any)
const AuthenticatedCompaniesNewRoute =
  AuthenticatedCompaniesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedCompaniesRoute,
  } as any)
const AuthenticatedCompaniesIdRoute =
  AuthenticatedCompaniesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedCompaniesRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/companies': typeof AuthenticatedCompaniesRouteWithChildren
  '/contacts': typeof AuthenticatedContactsRouteWithChildren
  '/knowledge': typeof AuthenticatedKnowledgeRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tasks': typeof AuthenticatedTasksRouteWithChildren
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/companies/$id': typeof AuthenticatedCompaniesIdRoute
  '/companies/new': typeof AuthenticatedCompaniesNewRoute
  '/contacts/$id': typeof AuthenticatedContactsIdRoute
  '/contacts/new': typeof AuthenticatedContactsNewRoute
  '/journeys/$id': typeof AuthenticatedJourneysIdRoute
  '/journeys/new': typeof AuthenticatedJourneysNewRoute
  '/knowledge/$id': typeof AuthenticatedKnowledgeIdRoute
  '/knowledge/new': typeof AuthenticatedKnowledgeNewRoute
  '/tasks/$id': typeof AuthenticatedTasksIdRoute
  '/tasks/new': typeof AuthenticatedTasksNewRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/companies': typeof AuthenticatedCompaniesRouteWithChildren
  '/contacts': typeof AuthenticatedContactsRouteWithChildren
  '/knowledge': typeof AuthenticatedKnowledgeRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tasks': typeof AuthenticatedTasksRouteWithChildren
  '/': typeof AuthenticatedIndexRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/companies/$id': typeof AuthenticatedCompaniesIdRoute
  '/companies/new': typeof AuthenticatedCompaniesNewRoute
  '/contacts/$id': typeof AuthenticatedContactsIdRoute
  '/contacts/new': typeof AuthenticatedContactsNewRoute
  '/journeys/$id': typeof AuthenticatedJourneysIdRoute
  '/journeys/new': typeof AuthenticatedJourneysNewRoute
  '/knowledge/$id': typeof AuthenticatedKnowledgeIdRoute
  '/knowledge/new': typeof AuthenticatedKnowledgeNewRoute
  '/tasks/$id': typeof AuthenticatedTasksIdRoute
  '/tasks/new': typeof AuthenticatedTasksNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/companies': typeof AuthenticatedCompaniesRouteWithChildren
  '/_authenticated/contacts': typeof AuthenticatedContactsRouteWithChildren
  '/_authenticated/knowledge': typeof AuthenticatedKnowledgeRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/companies/$id': typeof AuthenticatedCompaniesIdRoute
  '/_authenticated/companies/new': typeof AuthenticatedCompaniesNewRoute
  '/_authenticated/contacts/$id': typeof AuthenticatedContactsIdRoute
  '/_authenticated/contacts/new': typeof AuthenticatedContactsNewRoute
  '/_authenticated/journeys/$id': typeof AuthenticatedJourneysIdRoute
  '/_authenticated/journeys/new': typeof AuthenticatedJourneysNewRoute
  '/_authenticated/knowledge/$id': typeof AuthenticatedKnowledgeIdRoute
  '/_authenticated/knowledge/new': typeof AuthenticatedKnowledgeNewRoute
  '/_authenticated/tasks/$id': typeof AuthenticatedTasksIdRoute
  '/_authenticated/tasks/new': typeof AuthenticatedTasksNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/companies'
    | '/contacts'
    | '/knowledge'
    | '/profile'
    | '/settings'
    | '/tasks'
    | '/admin/users'
    | '/companies/$id'
    | '/companies/new'
    | '/contacts/$id'
    | '/contacts/new'
    | '/journeys/$id'
    | '/journeys/new'
    | '/knowledge/$id'
    | '/knowledge/new'
    | '/tasks/$id'
    | '/tasks/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/companies'
    | '/contacts'
    | '/knowledge'
    | '/profile'
    | '/settings'
    | '/tasks'
    | '/'
    | '/admin/users'
    | '/companies/$id'
    | '/companies/new'
    | '/contacts/$id'
    | '/contacts/new'
    | '/journeys/$id'
    | '/journeys/new'
    | '/knowledge/$id'
    | '/knowledge/new'
    | '/tasks/$id'
    | '/tasks/new'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/companies'
    | '/_authenticated/contacts'
    | '/_authenticated/knowledge'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/_authenticated/tasks'
    | '/_authenticated/'
    | '/_authenticated/admin/users'
    | '/_authenticated/companies/$id'
    | '/_authenticated/companies/new'
    | '/_authenticated/contacts/$id'
    | '/_authenticated/contacts/new'
    | '/_authenticated/journeys/$id'
    | '/_authenticated/journeys/new'
    | '/_authenticated/knowledge/$id'
    | '/_authenticated/knowledge/new'
    | '/_authenticated/tasks/$id'
    | '/_authenticated/tasks/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/knowledge': {
      id: '/_authenticated/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AuthenticatedKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contacts': {
      id: '/_authenticated/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedContactsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/companies': {
      id: '/_authenticated/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof AuthenticatedCompaniesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tasks/new': {
      id: '/_authenticated/tasks/new'
      path: '/new'
      fullPath: '/tasks/new'
      preLoaderRoute: typeof AuthenticatedTasksNewRouteImport
      parentRoute: typeof AuthenticatedTasksRoute
    }
    '/_authenticated/tasks/$id': {
      id: '/_authenticated/tasks/$id'
      path: '/$id'
      fullPath: '/tasks/$id'
      preLoaderRoute: typeof AuthenticatedTasksIdRouteImport
      parentRoute: typeof AuthenticatedTasksRoute
    }
    '/_authenticated/knowledge/new': {
      id: '/_authenticated/knowledge/new'
      path: '/new'
      fullPath: '/knowledge/new'
      preLoaderRoute: typeof AuthenticatedKnowledgeNewRouteImport
      parentRoute: typeof AuthenticatedKnowledgeRoute
    }
    '/_authenticated/knowledge/$id': {
      id: '/_authenticated/knowledge/$id'
      path: '/$id'
      fullPath: '/knowledge/$id'
      preLoaderRoute: typeof AuthenticatedKnowledgeIdRouteImport
      parentRoute: typeof AuthenticatedKnowledgeRoute
    }
    '/_authenticated/journeys/new': {
      id: '/_authenticated/journeys/new'
      path: '/journeys/new'
      fullPath: '/journeys/new'
      preLoaderRoute: typeof AuthenticatedJourneysNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/journeys/$id': {
      id: '/_authenticated/journeys/$id'
      path: '/journeys/$id'
      fullPath: '/journeys/$id'
      preLoaderRoute: typeof AuthenticatedJourneysIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contacts/new': {
      id: '/_authenticated/contacts/new'
      path: '/new'
      fullPath: '/contacts/new'
      preLoaderRoute: typeof AuthenticatedContactsNewRouteImport
      parentRoute: typeof AuthenticatedContactsRoute
    }
    '/_authenticated/contacts/$id': {
      id: '/_authenticated/contacts/$id'
      path: '/$id'
      fullPath: '/contacts/$id'
      preLoaderRoute: typeof AuthenticatedContactsIdRouteImport
      parentRoute: typeof AuthenticatedContactsRoute
    }
    '/_authenticated/companies/new': {
      id: '/_authenticated/companies/new'
      path: '/new'
      fullPath: '/companies/new'
      preLoaderRoute: typeof AuthenticatedCompaniesNewRouteImport
      parentRoute: typeof AuthenticatedCompaniesRoute
    }
    '/_authenticated/companies/$id': {
      id: '/_authenticated/companies/$id'
      path: '/$id'
      fullPath: '/companies/$id'
      preLoaderRoute: typeof AuthenticatedCompaniesIdRouteImport
      parentRoute: typeof AuthenticatedCompaniesRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedCompaniesRouteChildren {
  AuthenticatedCompaniesIdRoute: typeof AuthenticatedCompaniesIdRoute
  AuthenticatedCompaniesNewRoute: typeof AuthenticatedCompaniesNewRoute
}

const AuthenticatedCompaniesRouteChildren: AuthenticatedCompaniesRouteChildren =
  {
    AuthenticatedCompaniesIdRoute: AuthenticatedCompaniesIdRoute,
    AuthenticatedCompaniesNewRoute: AuthenticatedCompaniesNewRoute,
  }

const AuthenticatedCompaniesRouteWithChildren =
  AuthenticatedCompaniesRoute._addFileChildren(
    AuthenticatedCompaniesRouteChildren,
  )

interface AuthenticatedContactsRouteChildren {
  AuthenticatedContactsIdRoute: typeof AuthenticatedContactsIdRoute
  AuthenticatedContactsNewRoute: typeof AuthenticatedContactsNewRoute
}

const AuthenticatedContactsRouteChildren: AuthenticatedContactsRouteChildren = {
  AuthenticatedContactsIdRoute: AuthenticatedContactsIdRoute,
  AuthenticatedContactsNewRoute: AuthenticatedContactsNewRoute,
}

const AuthenticatedContactsRouteWithChildren =
  AuthenticatedContactsRoute._addFileChildren(
    AuthenticatedContactsRouteChildren,
  )

interface AuthenticatedKnowledgeRouteChildren {
  AuthenticatedKnowledgeIdRoute: typeof AuthenticatedKnowledgeIdRoute
  AuthenticatedKnowledgeNewRoute: typeof AuthenticatedKnowledgeNewRoute
}

const AuthenticatedKnowledgeRouteChildren: AuthenticatedKnowledgeRouteChildren =
  {
    AuthenticatedKnowledgeIdRoute: AuthenticatedKnowledgeIdRoute,
    AuthenticatedKnowledgeNewRoute: AuthenticatedKnowledgeNewRoute,
  }

const AuthenticatedKnowledgeRouteWithChildren =
  AuthenticatedKnowledgeRoute._addFileChildren(
    AuthenticatedKnowledgeRouteChildren,
  )

interface AuthenticatedTasksRouteChildren {
  AuthenticatedTasksIdRoute: typeof AuthenticatedTasksIdRoute
  AuthenticatedTasksNewRoute: typeof AuthenticatedTasksNewRoute
}

const AuthenticatedTasksRouteChildren: AuthenticatedTasksRouteChildren = {
  AuthenticatedTasksIdRoute: AuthenticatedTasksIdRoute,
  AuthenticatedTasksNewRoute: AuthenticatedTasksNewRoute,
}

const AuthenticatedTasksRouteWithChildren =
  AuthenticatedTasksRoute._addFileChildren(AuthenticatedTasksRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedCompaniesRoute: typeof AuthenticatedCompaniesRouteWithChildren
  AuthenticatedContactsRoute: typeof AuthenticatedContactsRouteWithChildren
  AuthenticatedKnowledgeRoute: typeof AuthenticatedKnowledgeRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedJourneysIdRoute: typeof AuthenticatedJourneysIdRoute
  AuthenticatedJourneysNewRoute: typeof AuthenticatedJourneysNewRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCompaniesRoute: AuthenticatedCompaniesRouteWithChildren,
  AuthenticatedContactsRoute: AuthenticatedContactsRouteWithChildren,
  AuthenticatedKnowledgeRoute: AuthenticatedKnowledgeRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedJourneysIdRoute: AuthenticatedJourneysIdRoute,
  AuthenticatedJourneysNewRoute: AuthenticatedJourneysNewRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
